version: '3.2'

services:
  ai-interview:
    image: ai-interview
    container_name: ai_interview_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local 
    restart: always
