name: CI/CD for Next.js with PostgreSQL (Neon), Drizzle ORM, and Gemini API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Build Next.js application
      - name: Build Next.js App
        env:
          NEXT_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT }}
          NEXT_APPWRITE_KEY: ${{ secrets.NEXT_APPWRITE_KEY }}
          NEXT_PUBLIC_APPWRITE_PROJECT: ${{ secrets.NEXT_PUBLIC_APPWRITE_PROJECT }}
          NEXT_PUBLIC_APPWRITE_DATABASE: ${{ secrets.NEXT_PUBLIC_APPWRITE_DATABASE }}
          NEXT_PUBLIC_APPWRITE_USERS_COLLECTION: ${{ secrets.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION }}
          NEXT_PUBLIC_APPWRITE_FILES_COLLECTION: ${{ secrets.NEXT_PUBLIC_APPWRITE_FILES_COLLECTION }}
          NEXT_PUBLIC_APPWRITE_BUCKET: ${{ secrets.NEXT_PUBLIC_APPWRITE_BUCKET }}
          NEXT_PUBLIC_DRIZZLE_DB_URL: ${{ secrets.NEXT_PUBLIC_DRIZZLE_DB_URL }}
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_INTERVIEW_QUESTION_COUNT: ${{ secrets.NEXT_PUBLIC_INTERVIEW_QUESTION_COUNT }}
          NEXT_PUBLIC_INFORMATION: ${{ secrets.NEXT_PUBLIC_INFORMATION }}
          NEXT_PUBLIC_QUESTION_NOTE: ${{ secrets.NEXT_PUBLIC_QUESTION_NOTE }}
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
          working-directory: ./
          github-token: ${{ secrets.G_TOKEN }}
